AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Daily Bloxx pull request reminder

Parameters:
  GithubOrg:
    Type: String
  GithubToken:
    Type: String
  SlackBotToken:
    Type: String
  SlackChannel:
    Type: String
  RunNumber:
    Type: String

  FunctionName:
    Type: String
    Default: slack-pr-reminder

 

Resources:
  LambdaLayer:
    Type: "AWS::Lambda::LayerVersion"
    Properties:
      CompatibleRuntimes:
        - python3.10
      Content:
        S3Bucket: slack-pr-notify-lambda
        S3Key: dependencies.zip
      LayerName: SlackNotifyPackages

  LambdaFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: !Ref FunctionName
      Events: !GetAtt LambdaSchedule
      Description: Daily Bloxx pull request reminder
      Runtime: python3.10
      Handler: main.main
      Timeout: 55
      CodeUri:
        Bucket: slack-pr-notify-lambda
        Key: !Sub "Slack-Event-Notify-${RunNumber}.zip"
      Layers:
        - !Ref LambdaLayer
      Environment:
        Variables:
          REMIND_GITHUB_ORG: !Ref GithubOrg
          REMIND_GITHUB_TOKEN: !Ref GithubToken
          REMIND_SLACK_BOT_TOKEN: !Ref SlackBotToken
          REMIND_SLACK_CHANNEL: !Ref SlackChannel
      Events:
        LambdaSchedule:
          Type: Schedule
          Properties:
            Schedule: 'cron(30 7 ? * mon-fri *)'
            Name: pr-notify-schedule
            Description: Lambda notify schedule for Pull Requests
            Enabled: true
